name: CI/CD
on:
  push:
    branches: [ "main" ]
  merge_group:
  pull_request:
    branches:
      - main
jobs:
  tests:
    name: Run Unit Tests
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        env:
          runner: self-hosted
        with:
          coverage: xdebug
          tools: composer
          php-version: '8.2'
          extensions: mbstring xdebug dom

      - name: Install Dependencies
        run: composer install --optimize-autoloader

      - name: Run Unit Tests
        run: vendor/bin/pest --coverage-xml=coverage.xml
